services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - postgres
    networks:
      - bot-network

  redis:
    container_name: haze_cache
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    networks:
      - bot-network

  postgres:
    container_name: haze_database
    image: postgres:14
    environment:
      POSTGRES_DB: haze_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: hazeasmin1234
    ports:
      - "5432:5432"
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
