services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redzone-bot
    restart: always
    depends_on:
      - redis
      - postgres
    environment:
      - TOKEN=${TOKEN}
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
    networks:
      - bot-network
  redis:
    container_name: redzone-redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - bot-network
    command: redis-server --save 60 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - redis:/data
  postgres:
    container_name: redzone-database
    image: postgres:latest
    environment:
      POSTGRES_DB: redzone_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: redzoneadmin
    ports:
      - "5432:5432"
    networks:
      - bot-network

networks:
  bot-network:

volumes:
  redis:
    driver: local
  psql_volume:
